// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgxBhWgtmRA_cc-JcuMP8fXl7NjZIthOI',
    appId: '1:951311475019:web:d65cfc2cbe6e987c89c8ce',
    messagingSenderId: '951311475019',
    projectId: 'orgami-66nxok',
    authDomain: 'orgami-66nxok.firebaseapp.com',
    storageBucket: 'orgami-66nxok.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf1t5cToh1UoF7R52vTSJxMajw8CvmVUA',
    appId: '1:951311475019:android:83ce358b010643ba89c8ce',
    messagingSenderId: '951311475019',
    projectId: 'orgami-66nxok',
    storageBucket: 'orgami-66nxok.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-PFyqhP5aEVE6XwGku3jMe91G3efMaVw',
    appId: '1:951311475019:web:c6d429ef1386b91d89c8ce',
    messagingSenderId: '951311475019',
    projectId: 'orgami-66nxok',
    authDomain: 'orgami-66nxok.firebaseapp.com',
    storageBucket: 'orgami-66nxok.appspot.com',
  );
}
